// shiny new nocturne jobs

#define JOB_FARMER "Farmer"
#define JOB_RESTAURANT "Restaurant Employee"
#define JOB_SALON "Salon Worker"

#define JOB_TOWNHALL_CLERK "Deputy Clerk"
#define JOB_TOWNHALL_MAYORAIDE "Mayor's Aide"

#define JOB_MAGADON_CORP_HEAD "Clinic Head Manager"
#define JOB_MAGADON_CORP_MIDDLE_MANAGER "Clinic Middle Manager"
#define JOB_MAGADON_SECURITY_CHIEF "Clinic Security Chief"
#define JOB_MAGADON_SECURITY "Clinic Security Officer"
#define JOB_MAGADON_DOCTOR "Clinic Doctor"

#define JOB_HUNTER_CELL_HEAD "Hunter Field Lead"
#define JOB_HUNTER_CELL_SOLDIER "Hunter Pointman"

// department display order
#define DEPARTMENT_DISPLAY_ORDER_CAMARILLA 1
#define DEPARTMENT_DISPLAY_ORDER_CHURCH 2
#define DEPARTMENT_DISPLAY_ORDER_CLINIC 3
#define DEPARTMENT_DISPLAY_ORDER_STRIP_CLUB 4
#define DEPARTMENT_DISPLAY_ORDER_ANARCH 5
#define DEPARTMENT_DISPLAY_ORDER_GIOVANNI 6
#define DEPARTMENT_DISPLAY_ORDER_CHANTRY 7
#define DEPARTMENT_DISPLAY_ORDER_MANOR 8
#define DEPARTMENT_DISPLAY_ORDER_SABBAT 9
#define DEPARTMENT_DISPLAY_ORDER_GAIA 10
#define DEPARTMENT_DISPLAY_ORDER_PENTEX 11
#define DEPARTMENT_DISPLAY_ORDER_SUPPLY 12
#define DEPARTMENT_DISPLAY_ORDER_POLICE 13
#define DEPARTMENT_DISPLAY_ORDER_CITY_SERVICES 14
#define DEPARTMENT_DISPLAY_ORDER_SOCIETY_OF_LEOPOLD 15
#define DEPARTMENT_DISPLAY_ORDER_MAGADON 16
#define DEPARTMENT_DISPLAY_ORDER_HUNTER 17
#define DEPARTMENT_DISPLAY_ORDER_CITIZEN 18
